/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package protocols.avro;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Light {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Light\",\"namespace\":\"protocols.avro\",\"types\":[],\"messages\":{\"LightSwitch\":{\"request\":[],\"response\":\"null\"},\"GetLightState\":{\"request\":[],\"response\":\"boolean\"},\"IsAlive\":{\"request\":[],\"response\":\"boolean\"}}}");
  java.lang.Void LightSwitch() throws org.apache.avro.AvroRemoteException;
  boolean GetLightState() throws org.apache.avro.AvroRemoteException;
  boolean IsAlive() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Light {
    public static final org.apache.avro.Protocol PROTOCOL = protocols.avro.Light.PROTOCOL;
    void LightSwitch(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void GetLightState(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void IsAlive(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}